INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Juan Jose' , 'Ortiz Santa' , 'jjortizsanta97@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Maria Camila' , 'Ortiz gil' , 'mcortizgil@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Angie Maria' , 'Ortiz Santa' , 'angie-or@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Luz Mery' , 'Santa Velez' , 'luz-sy@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jose Isaias' , 'Bermudez' , 'isaias7561@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jerameel' , 'Santa' , 'Jeramel@gmail.com', '2022-08-01')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Juan Jose' , 'Ortiz Santa' , 'jjoratizsanta97@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Maria Camila' , 'Ortiz gil' , 'mcoartizgil@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Angie Maria' , 'Ortiz Santa' , 'angiae-or@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Luz Mery' , 'Santa Velez' , 'luz-sya@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jose Isaias' , 'Bermudez' , 'isaiasa7561@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jerameel' , 'Santa' , 'Jeramea@gmail.com', '2022-08-01')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Juan Jose' , 'Ortiz Santa' , 'ljjoratizsanta97@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Maria Camila' , 'Ortiz gil' , 'lmcoartizgil@gmail.com', '2022-07-30')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Angie Maria' , 'Ortiz Santa' , 'langiae-or@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Luz Mery' , 'Santa Velez' , 'lluz-sya@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jose Isaias' , 'Bermudez' , 'lisaiasa7561@gmail.com', '2022-07-31')
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES ('Jerameel' , 'Santa' , 'lJeramea@gmail.com', '2022-08-01')